# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Line For Android Firebase App Distruation"

  lane :firebase_distribution do
    firebase_app_distribution(
          app: "1:329896472724:android:07800e2154f665eaca8481",
          firebase_cli_token: "1//037Vi0KLg-HlSCgYIARAAGAMSNwF-L9IrYeCX6ovCp6wp79hCV05nrIamrJUw5hFqyLZKxvEGiFDiZyYANEvjAyhhVMI3xZSwuuQ",
          android_artifact_type: "APK",  # or "AAB" if you're using an Android App Bundle
          apk_path: "../build/app/outputs/apk/production/release/app-production-release.apk",
          release_notes: "First Fastlane Firebase Distribution"
       )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
